// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MapInfo","status":true,"description":"在大地圖左上角顯示地點與時間","parameters":{}},
{"name":"CustomCharacterScale","status":false,"description":"[V1.1] 強力大型行走圖縮放插件","parameters":{}},
{"name":"AutoBlink","status":false,"description":"[V1.0] 自動眨眼系統","parameters":{}},
{"name":"Gabriel_Core","status":true,"description":"[V2.0] Gabriel 專用：大圖縮放 + 自動眨眼一體化插件","parameters":{}},
{"name":"OverLight","status":true,"description":"[V1.1] 備註式地圖光影疊加 (蓋在人物上方)","parameters":{}},
{"name":"OverLayer_Shadow","status":true,"description":"[V1.2] 備註式地圖陰影疊加 (蓋在人物上方)","parameters":{}},
{"name":"RegionPassage","status":true,"description":"[V1.0] 區域 ID 碰撞插件 (讓彩色數字變成牆壁)","parameters":{}},
{"name":"MyCustomMessage","status":true,"description":"","parameters":{}},
{"name":"BookReader","status":true,"description":"獨立讀書系統 - 專門處理全螢幕文本與字條","parameters":{"BookModeSwitch":"10","NoteModeSwitch":"11"}}
];
